CREATE TABLE app_user (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          email VARCHAR(255) NOT NULL UNIQUE,
                          password_hash VARCHAR(255) NOT NULL,
                          display_name VARCHAR(150) NOT NULL,
                          manager_id BIGINT,
                          is_active BOOLEAN NOT NULL DEFAULT TRUE,
                          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                          updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                          CONSTRAINT fk_app_user_manager
                              FOREIGN KEY (manager_id)
                                  REFERENCES app_user (id)
                                  ON DELETE RESTRICT,

                          CONSTRAINT chk_app_user_not_own_manager
                              CHECK (manager_id IS NULL OR manager_id <> id)
);

CREATE TABLE role (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      code VARCHAR(50) NOT NULL UNIQUE,
                      description VARCHAR(255)
);

CREATE TABLE user_role (
                           user_id BIGINT NOT NULL,
                           role_id BIGINT NOT NULL,
                           assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                           CONSTRAINT pk_user_role
                               PRIMARY KEY (user_id, role_id),

                           CONSTRAINT fk_user_role_user
                               FOREIGN KEY (user_id)
                                   REFERENCES app_user (id)
                                   ON DELETE RESTRICT,

                           CONSTRAINT fk_user_role_role
                               FOREIGN KEY (role_id)
                                   REFERENCES role (id)
                                   ON DELETE RESTRICT
);

CREATE INDEX idx_user_role_role_id
    ON user_role (role_id);